const { ROOT_PATH } = require('./militaryTree.he');
const P = ROOT_PATH;
const SYSTEMS = ['hr-core', 'idm', 'training', 'ops-roster', 'logistics'];
const PROFESSIONS = ['פיתוח', 'תשתיות', 'מבצעים', 'לוגיסטיקה', 'מודיעין', 'הדרכה', 'אבטחת מידע'];
const AVATAR_COLORS = ['111827', '1f2937', '334155', '0f766e', '4338ca', '7c3aed', 'be123c'];
const SHAREPOINT_PROFILE_FIELDS = [
    'UserProfile_GUID',
    'SID',
    'ADGuid',
    'AccountName',
    'FirstName',
    'SPS-PhoneticFirstName',
    'LastName',
    'SPS-PhoneticLastName',
    'PreferredName',
    'SPS-PhoneticDisplayName',
    'WorkPhone',
    'Department',
    'Title',
    'SPS-Department',
    'Manager',
    'AboutMe',
    'PersonalSpace',
    'PictureURL',
    'UserName',
    'QuickLinks',
    'WebSite',
    'PublicSiteRedirect',
    'SPS-JobTitle',
    'SPS-DataSource',
    'SPS-MemberOf',
    'SPS-Dotted-line',
    'SPS-Peers',
    'SPS-Responsibility',
    'SPS-SipAddress',
    'SPS-MySiteUpgrade',
    'SPS-DontSuggestList',
    'SPS-ProxyAddresses',
    'SPS-HireDate',
    'SPS-DisplayOrder',
    'SPS-ClaimID',
    'SPS-ClaimProviderID',
    'SPS-LastColleagueAdded',
    'SPS-OWAUrl',
    'SPS-ResourceSID',
    'SPS-ResourceAccountName',
    'SPS-MasterAccountName',
    'SPS-UserPrincipalName',
    'SPS-O15FirstRunExperience',
    'SPS-PersonalSiteInstantiationState',
    'SPS-PersonalSiteNumberOfRetries',
    'SPS-PersonalSiteFirstCreationError',
    'SPS-FeedIdentifier',
    'WorkEmail',
    'CellPhone',
    'Fax',
    'HomePhone',
    'Office',
    'SPS-Location',
    'Assistant',
    'SPS-PastProjects',
    'SPS-Skills',
    'SPS-School',
    'SPS-Birthday',
    'SPS-StatusNotes',
    'SPS-Interests',
    'SPS-HashTags',
    'SPS-EmailOptin',
    'SPS-PrivacyPeople',
    'SPS-PrivacyActivity',
    'SPS-PictureTimestamp',
    'SPS-PicturePlaceholderState',
    'SPS-PictureExchangeSyncState',
    'SPS-MUILanguages',
    'SPS-ContentLanguages',
    'SPS-TimeZone',
    'SPS-RegionalSettings-FollowWeb',
    'SPS-Locale',
    'SPS-CalendarType',
    'SPS-AltCalendarType',
    'SPS-AdjustHijriDays',
    'SPS-ShowWeeks',
    'SPS-WorkDays',
    'SPS-WorkDayStartHour',
    'SPS-WorkDayEndHour',
    'SPS-Time24',
    'SPS-FirstDayOfWeek',
    'SPS-FirstWeekOfYear',
    'SPS-RegionalSettings-Initialized',
    'OfficeGraphEnabled',
    'SPS-UserType',
    'SPS-HideFromAddressLists',
    'SPS-RecipientTypeDetails',
    'DelveFlags',
    'VideoUserPopup',
    'PulseMRUPeople',
    'msOnline-ObjectId',
    'SPS-PointPublishingUrl',
    'SPS-TenantInstanceId',
    'SPS-SharePointHomeExperienceState',
    'SPS-MultiGeoFlags',
];
function demoProfileImageUrl(firstName, lastName, index) {
    const initials = `${firstName[0] ?? ''}${lastName[0] ?? ''}` || String(index + 1).padStart(2, '0');
    const color = AVATAR_COLORS[index % AVATAR_COLORS.length];
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160"><rect width="160" height="160" rx="32" fill="#${color}"/><text x="80" y="94" text-anchor="middle" font-size="52" font-family="Arial, sans-serif" font-weight="700" fill="#fff">${initials}</text></svg>`;
    return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}
function demoSharePointProfile(params) {
    const profile = Object.fromEntries(SHAREPOINT_PROFILE_FIELDS.map((key) => [key, '']));
    const account = `idf\\${params.personalNumber}`;
    const fullName = `${params.firstName} ${params.lastName}`;
    const title = [params.rank, params.role].filter(Boolean).join(' ');
    return {
        ...profile,
        UserProfile_GUID: `demo-profile-${String(params.index + 1).padStart(3, '0')}`,
        SID: `S-1-5-21-DEMO-${params.index + 1}`,
        ADGuid: `demo-ad-${String(params.index + 1).padStart(3, '0')}`,
        AccountName: account,
        FirstName: params.firstName,
        LastName: params.lastName,
        PreferredName: fullName,
        WorkPhone: params.phone,
        Department: params.rawOrgPath,
        Title: title,
        'SPS-Department': params.rawOrgPath,
        Manager: params.index === 0 ? '' : 'idf\\DEMO-2001',
        PictureURL: params.profileImageUrl,
        UserName: params.email,
        'SPS-JobTitle': params.role ?? '',
        'SPS-DataSource': params.sourceSystem,
        'SPS-MemberOf': params.rawOrgPath,
        'SPS-SipAddress': params.email,
        'SPS-ClaimID': `i:0#.w|${account}`,
        'SPS-ClaimProviderID': 'Windows',
        'SPS-ResourceAccountName': account,
        'SPS-MasterAccountName': account,
        'SPS-UserPrincipalName': params.email,
        WorkEmail: params.email,
        CellPhone: params.phone,
        Office: params.rawOrgPath.split(/[\\/]/).filter(Boolean).at(-2) ?? '',
        'SPS-Location': params.rawOrgPath,
        'SPS-Skills': ['פיקוד', 'מערכות', 'תפעול'][params.index % 3],
        'SPS-UserType': 'חייל',
        'msOnline-ObjectId': `demo-online-${String(params.index + 1).padStart(3, '0')}`,
    };
}
const PEOPLE = [
    ['demo-01', 'DEMO-2001', 'יונתן', 'הררי', 'סרן', 'קמ"ד דיגיטל', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות א׳/יונתן הררי`, 'מנהל דמו, מפקד צוות א׳ קיים', 'clean', 'admin'],
    ['demo-02', 'DEMO-2004', 'נדב', 'שפירא', 'סרן', 'מפקד צוות ב׳', `${P}\\אגף התקשוב\\ענף צפון\\מדור תומר\\צוות ב׳\\נדב שפירא`, 'משתמש רגיל דמו, מפקד צוות ב׳ עם מפריד backslash', 'normalize', 'regular'],
    ['demo-03', 'DEMO-2101', 'מאיה', 'רוזן', 'סמ"ר', 'מפתחת Fullstack', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות א׳/מאיה רוזן`, 'חיילת בצוות קיים', 'clean'],
    ['demo-04', 'DEMO-2102', 'עומר', 'לביא', 'סמל', 'בודק תוכנה', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות ב׳/עומר לביא`, 'חייל בצוות קיים', 'clean'],
    ['demo-05', 'DEMO-2103', 'שחר', 'ברק', 'סרן', 'קמ"ד תשתיות', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות ג׳/שחר ברק`, 'צוות ג׳ אמור להיווצר תחת מדור תומר', 'new_unit'],
    ['demo-06', 'DEMO-2104', 'נועה', 'אדרי', 'סמ"ר', 'אחראית ניטור', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות ג׳/נועה אדרי`, 'חיילת שנייה באותה יחידה חדשה', 'new_unit'],
    ['demo-07', 'DEMO-2105', 'דניאל', 'מזרחי', 'רס"ן', 'רת"ח מערכות', `${P}/אגף התקשוב/ענף דרום/מדור אמיר/צוות א׳/דניאל מזרחי`, 'ענף דרום ומדור אמיר לא קיימים בבסיס', 'new_unit'],
    ['demo-08', 'DEMO-2106', 'ליהי', 'ממן', 'סגן', 'מפקדת צוות', `${P}/אגף התקשוב/ענף דרום/מדור אמיר/צוות ב׳/ליהי ממן`, 'צוות נוסף תחת ענף חדש', 'new_unit'],
    ['demo-09', 'DEMO-2107', 'בן', 'דרור', 'סמל', 'טכנאי קשר', `${P}/אגף התקשבות/ענף צפון/מדור תומר/צוות א׳/בן דרור`, 'אגף התקשבות צריך להילמד ככינוי לאגף התקשוב', 'alias'],
    ['demo-10', 'DEMO-2108', 'קובי', 'וקנין', 'סמ"ר', 'מפעיל מערכות', `${P}/אגף התקשוב/ענף צפון/מדור תמר/צוות א׳/קובי וקנין`, 'מדור תמר ככינוי למדור תומר', 'alias'],
    ['demo-11', 'DEMO-2109', 'רוני', 'שחר', 'סמל', 'חוקר נתונים', `${P}/אגף התקשוב/מדור תומר/צוות א׳/רוני שחר`, 'חסר ענף צפון באמצע, צריך להשלים לבד', 'missing'],
    ['demo-12', 'DEMO-2110', 'יעל', 'ניסן', 'סגן', 'מפקדת צוות', `${P}/אגף התקשוב/ענף צפון/צוות ב׳/יעל ניסן`, 'חסר מדור תומר באמצע', 'missing'],
    ['demo-13', 'DEMO-2111', 'טל', 'רובין', 'רב"ט', 'חייל צוות', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות ביתא/טל רובין`, 'צוות ביתא צריך להתאים לצוות ב׳', 'fuzzy'],
    ['demo-14', 'DEMO-2112', 'סתיו', 'אוחיון', 'סמל', 'חייל צוות', `${P}/אגף תקשוב/ענף צפוני/מדור תמר/צוות א/סתיו אוחיון`, 'כמה וריאציות כתיב באותו נתיב', 'fuzzy'],
    ['demo-15', 'DEMO-2113', 'גל', 'מאיר', 'רס"ן', 'רת"ח מובייל', `${P}/אגף הטכנולוגיה/ענף תוכנה/מדור מובייל/גל מאיר`, 'אגף טכנולוגיה שלם אמור להיווצר', 'new_unit'],
    ['demo-16', 'DEMO-2114', 'ורד', 'חסון', 'רס"ן', 'רת"ח DevOps', `${P}/אגף הטכנולוגיה/ענף תוכנה/מדור DevOps/ורד חסון`, 'מדור באנגלית בתוך ענף חדש', 'new_unit'],
    ['demo-17', 'DEMO-2115', 'אמיר', 'תורגמן', 'סרן', 'קמ"ד אבטחה', `${P}/אגף הטכנולוגיה/ענף תשתיות/מדור אבטחת מידע/אמיר תורגמן`, 'ענף תשתיות חדש', 'new_unit'],
    ['demo-18', 'DEMO-2116', 'כרם', 'אורן', 'סגן', 'מפקדת צוות ענן', `${P}/אגף הטכנולוגיה/ענף תשתיות/מדור ענן/צוות פלטפורמה/כרם אורן`, 'עומק חדש מלא', 'new_unit'],
    ['demo-19', 'DEMO-2117', 'טלי', 'רגב', 'סמ"ר', 'רכזת מלאי', `${P}/אגף הלוגיסטיקה/ענף אספקה/מדור מחסנים מזרח/צוות מלאי ג׳/טלי רגב`, 'הרחבת אגף קיים לענף/מדור חדש', 'new_unit'],
    ['demo-20', 'DEMO-2118', 'אלי', 'רוזן', 'רס"ן', 'רת"ח תחבורה', `${P}/אגף הלוגיסטיקה/ענף תחבורה/מדור שיירות 2/צוות נהגים ג׳/אלי רוזן`, 'משתמש קיים בשם דומה עובר לנתיב חדש', 'movement'],
    ['demo-21', 'DEMO-2119', 'הדס', 'מלכה', 'סרן', 'קמ"ד ציוד רפואי', `${P}/אגף הלוגיסטיקה/ענף לוגיסטיקה רפואית/מדור ציוד רפואי/הדס מלכה`, 'ענף רפואי חדש', 'new_unit'],
    ['demo-22', 'DEMO-2120', 'אודי', 'פישמן', 'סרן', 'קמ"ד שולחן', `${P}/אגף המודיעין/ענף ניתוח/מדור שולחן אלף/אודי פישמן`, 'שולחן אלף צריך להתאים לשולחן א׳', 'fuzzy'],
    ['demo-23', 'DEMO-2121', 'נעמה', 'גרבי', 'סמ"ר', 'אנליסטית', `${P}/אגף המודיעין/ענף מבצעים מודיעיניים/מדור שולחן ה׳/נעמה גרבי`, 'ענף מבצעים מודיעיניים חדש', 'new_unit'],
    ['demo-24', 'DEMO-2122', 'רועי', 'בוסקילה', 'סגן', 'מפקד צוות שטח', `${P}/אגף המודיעין/ענף איסוף/צוות שטח 4/רועי בוסקילה`, 'צוות שטח חדש', 'new_unit'],
    ['demo-25', 'DEMO-2123', 'עופר', 'בן שימון', 'סרן', 'קמ"ד מודלים', `${P}/אגף המודיעין/ענף ניתוח/מחלקת מחקר/תא מודלים/עופר בן שימון`, 'מחלקה ותא חדשים תחת ענף קיים', 'new_unit'],
    ['demo-26', 'DEMO-2124', 'גיא', 'נבון', 'רס"ן', 'רת"ח הכשרות בסיס', `${P}/אגף ההדרכה/ענף הכשרות בסיס/מדור פלוגה 1/מחלקה א׳/גיא נבון`, 'אגף הדרכה שלם אמור להיווצר', 'new_unit'],
    ['demo-27', 'DEMO-2125', 'הילה', 'מור', 'סרן', 'קמ"ד קורס קצינים', `${P}/אגף ההדרכה/ענף הכשרות מתקדמות/מדור קורס קצינים/הילה מור`, 'הכשרות מתקדמות חדש', 'new_unit'],
    ['demo-28', 'DEMO-2126', 'תום', 'ברקת', 'סמ"ר', 'מפעיל סימולציה', `${P}/אגף ההדרכה/ענף סימולציה/מדור מעבדת מציאות מדומה/תום ברקת`, 'סימולציה חדש', 'new_unit'],
    ['demo-29', 'DEMO-2127', 'ספיר', 'אדלר', 'רס"ן', 'רת"ח כוח אדם', `${P}/אגף משאבי אנוש/ענף כוח אדם/מדור גיוס/ספיר אדלר`, 'אגף משאבי אנוש חדש', 'new_unit'],
    ['demo-30', 'DEMO-2128', 'מיכל', 'דיין', 'סרן', 'קמ"ד בריאות הנפש', `${P}/אגף משאבי אנוש/ענף רווחה/מדור בריאות הנפש/מיכל דיין`, 'ענף רווחה חדש', 'new_unit'],
    ['demo-31', 'DEMO-2129', 'יובל', 'הרץ', 'רס"ן', 'רת"ח מבצעי שטח', `${P}/אגף המבצעים/ענף מבצעים שטח/מדור גדוד 1/פלוגה א׳/יובל הרץ`, 'אגף מבצעים חדש', 'new_unit'],
    ['demo-32', 'DEMO-2130', 'איתן', 'כהן', 'סרן', 'מפקד צוות סיירת', `${P}/אגף המבצעים/ענף מבצעים שטח/מחלקת סיירת מיוחדת/צוות סיירת א׳/איתן כהן`, 'עומק מבצעי חדש עם מפקד', 'new_unit'],
    ['demo-33', 'DEMO-2131', 'אורי', 'נחמני', 'סגן', 'מפקד מדור תכנון', `${P}/אגף המבצעים/ענף תכנון/מדור תכנון טקטי/אורי נחמני`, 'ענף תכנון חדש', 'new_unit'],
    ['demo-34', 'DEMO-2132', 'לירן', 'אטיאס', 'סמ"ר', 'לוחם צוות', `${P}/אגף המבצעים/ענף מבצעי שטח/מדור גדוד 1/פלוגה א׳/לירן אטיאס`, 'מבצעי שטח צריך להתאים למבצעים שטח', 'fuzzy'],
    ['demo-35', 'DEMO-2133', 'מור', 'דגן', 'סגן', 'מפקדת תא פיתוח', `${P}/אגף הטכנולוגיה/ענף תוכנה/מחלקת ארכיטקטורה/תא פיתוח/מור דגן`, 'תא פיתוח חדש', 'new_unit'],
    ['demo-36', 'DEMO-2134', 'עדי', 'נוימן', 'סמל', 'חיילת צוות', `${P}/אגף התקשוב/ענף צפון/מדור יעל/צוות ב׳/עדי נוימן`, 'מדור יעל חדש', 'new_unit'],
    ['demo-37', 'DEMO-2135', 'פלג', 'אשכנזי', 'סגן', 'מפקד צוות אותות', `${P}/אגף התקשוב/ענף מרכז/מדור אותות/צוות א׳/פלג אשכנזי`, 'ענף מרכז ומדור אותות חדשים', 'new_unit'],
    ['demo-38', 'DEMO-2136', 'דור', 'קליין', 'סרן', 'קמ"ד סייבר', `${P}/אגף התקשוב/ענף מרכז/מדור סייבר/צוות כחול/דור קליין`, 'מדור סייבר חדש', 'new_unit'],
    ['demo-39', 'DEMO-2137', 'מיכאל', 'שרון', 'סמל', 'חייל צוות', `${P}/אגף התקשוב/ענף צפון/מדור תומר/צוות ב׳/s9214482/מיכאל שרון`, 'נתיב עם מספר אישי באמצע, צריך לא ליצור ממנו יחידה', 'conflict'],
    ['demo-40', 'DEMO-2138', 'דנה', 'קורן', 'סמ"ר', 'תומכת מערכות', `${P}/אגף התקשוב/ענף צפון/מדור תומר/דנה קורן`, 'נתיב מסתיים בלי צוות; חיילת רגילה צריכה להיכנס לצוות תחת המדור', 'missing'],
];
const DEMO_USERS = PEOPLE.map((row, index) => {
    const [id, personalNumber, firstName, lastName, rank, role, rawOrgPath, description, category, accessRole,] = row;
    const serial = String(index + 1).padStart(3, '0');
    const email = `${personalNumber.toLowerCase()}@demo.idf.local`;
    const phone = `050-700-${serial}`;
    const sourceSystem = SYSTEMS[index % SYSTEMS.length];
    const profileImageUrl = demoProfileImageUrl(firstName, lastName, index);
    const sharePointProfile = demoSharePointProfile({
        personalNumber,
        firstName,
        lastName,
        rank,
        role,
        rawOrgPath,
        email,
        phone,
        profileImageUrl,
        sourceSystem,
        index,
    });
    return {
        id,
        personalNumber,
        firstName,
        lastName,
        rank,
        role,
        accessRole: accessRole,
        profileImageUrl,
        rawOrgPath,
        description,
        category: category,
        email,
        phone,
        sourceSystem,
        sharePointProfile,
        attributes: {
            sharePointProfile,
            employeeType: index % 6 === 0 ? 'commander' : 'soldier',
            profession: PROFESSIONS[index % PROFESSIONS.length],
            clearance: ['שמור', 'סודי', 'סודי ביותר'][index % 3],
            serviceType: index % 5 === 0 ? 'קבע' : 'חובה',
            active: true,
            importBatch: 'demo-rich-001',
            sourceLine: index + 1,
        },
    };
});
const DEMO_CATEGORIES = {
    clean: 'התאמה נקייה',
    normalize: 'נורמליזציה',
    typo: 'שגיאת כתיב',
    alias: 'כינוי / למידה',
    fuzzy: 'התאמה מטושטשת',
    missing: 'רמה חסרה',
    new_unit: 'יחידה חדשה',
    movement: 'מעבר ארגוני',
    conflict: 'קונפליקט',
};
function getDemoUserById(id) {
    return DEMO_USERS.find((u) => u.id === id);
}
function getDemoUsersByCategory(category) {
    return DEMO_USERS.filter((u) => u.category === category);
}

module.exports = { getDemoUserById, getDemoUsersByCategory, DEMO_USERS, DEMO_CATEGORIES };
